
services:
  # Сервис для Jupyter Lab
  jupyter_lab:
    build: .
    container_name: house_prices_gpu_container
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      - mlflow_server

  # Сервис для MLflow UI
  mlflow_server:
    build: .
    container_name: mlflow_ui_server
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri /app/mlruns
      --default-artifact-root /app/mlruns

  # Сервис для Optuna Dashboard
  optuna_dashboard:
    build: .
    container_name: optuna_dashboard_container
    ports:
      - "8081:8081" # 
    volumes:
      - .:/app # <-- Важно! Монтируем ту же папку, чтобы видеть optuna_study.db
    working_dir: /app
    command: >
      optuna-dashboard sqlite:////app/optuna_study.db --host 0.0.0.0 --port 8080